{% set version = "2.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinytoastr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinytoastr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinytoastr/shinytoastr_{{ version }}.tar.gz
  sha256: df903fb69a747f806a20396f63a0686b61b6bc410be0789235985a9594278efd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-shiny
  run:
    - r-base
    - r-shiny

test:
  commands:
    - $R -e "library('shinytoastr')"           # [not win]
    - "\"%R%\" -e \"library('shinytoastr')\""  # [win]

about:
  home: https://github.com/mangothecat/shinytoastr
  license: MIT
  summary: 'Browser notifications in ''Shiny'' apps, using ''toastr'': <https://github.com/CodeSeven/toastr#readme>.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinytoastr
# Title: Notifications from 'Shiny'
# Version: 2.1.1
# Author: John Papa, Tim Ferrell, Hans Fjallemark, Gabor Csardi
# Maintainer: Gabor Csardi <gcsardi@mango-solutions.com>
# Description: Browser notifications in 'Shiny' apps, using 'toastr': <https://github.com/CodeSeven/toastr#readme>.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/mangothecat/shinytoastr
# BugReports: https://github.com/mangothecat/shinytoastr/issues
# Imports: shiny
# RoxygenNote: 5.0.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2016-06-05 22:08:00 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2016-06-06 06:39:52
